name: app_position
description: "A new Flutter project."
publish_to: "none"
version: 0.1.0+2

environment:
  sdk: ">=3.2.3 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  camera: ^0.10.5+8 # Camera package
  google_mlkit_commons: ^0.9.0
  google_mlkit_pose_detection: ^0.13.0 # Pose detection
  # google_mlkit_commons: ^0.6.1 # google commons
  path_provider: ^2.1.1 # File path
  wakelock_plus: ^1.2.8
  flutter_tts: ^3.8.5 # TTS (Text to Speech)
  provider: ^6.1.1 # Provider for state management
  package_info_plus: ^8.1.1
  flutter_svg: ^2.0.2
  path: any
  duration_picker: ^1.1.1
  hive: ^2.2.3
  hive_flutter: ^1.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  hive_generator: ^2.0.1
  build_runner: ^2.4.9
  flutter_launcher_icons: ^0.13.1

dependency_overrides:
  win32: ^5.5.4

flutter_launcher_icons:
  ios: "Icon-App"
  android: true
  image_path: "assets/image/ic_launcher.png"
  adaptive_icon_background: "assets/image/ic_launcher_background.png" # only available for Android 8.0 devices and above
  adaptive_icon_foreground: "assets/image/ic_launcher_foreground.png" # only available for Android 8.0 devices and above
  adaptive_icon_monochrome: "assets/image/ic_launcher_monochrome.png" # only available for Android 13 devices and above
  min_sdk_android: 21
  remove_alpha_ios: true
  background_color_ios: "#ffffff"

flutter:
  uses-material-design: true

  assets:
    - assets/fonts/
    - assets/image/
    - assets/svg/
    - assets/image/collaborators/
    - assets/image/logos/
